spring:
  application:
    name: lite-gateway-sample

lite:
  gateway:
    routes:
      - id: test-route
        uri: https://httpbin.org
        predicates:
          - name: Method
            args: GET
        order: 1
      - id: mock1
        uri: http://localhost:18080
        predicates:
          - name: Path
            args: /mock1/ok
        order: 2

logging:
  level:
    root: info
    lite.gateway: debug