spring:
  application:
    name: lite-gateway-sample

lite:
  gateway:
    routes:
    - id: test-route
      uri: https://httpbin.org
      predicates:
        - name: Method
          args: GET
      order: 1
    - id: jsonplaceholder-route
      uri: https://jsonplaceholder.typicode.com
      predicates:
        - name: Method
          args: POST
        - name: Path
          args: /posts/**
      order: 2
    - id: postman-echo-route
      uri: https://postman-echo.com
      predicates:
        - name: Path
          args: /post/**
        - name: Header
          args: "Content-Type, multipart/form-data.*"
      order: 3
logging:
  level:
    root: info
    lite.gateway: debug